In [2]:
import numpy as np
import pandas as pd

## Numpy arrays

In [9]:
arr = [[2 , 3, 5 ] , [5 , 7, 20] , [23 , 45 , 64]]
arr

[[2, 3, 5], [5, 7, 20], [23, 45, 64]]

In [10]:
arr = np.array(arr)
arr

array([[ 2,  3,  5],
       [ 5,  7, 20],
       [23, 45, 64]])

In [11]:
np.arange( 10 , 350 , 25) #start stop and step size

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235, 260, 285, 310,
       335])

In [31]:
np.linspace(0 , 5 , 6) # start stop and no. values

array([0., 1., 2., 3., 4., 5.])

In [22]:
np.zeros((2 , 2,  3 , 2, 1)) #dimensions n* n* ... * row * column

array([[[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]],



       [[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]],


        [[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
 np.eye(3) # identity square matrix n*n dim

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### uniform distribution
<img src="uni-dist.png">

In [39]:
np.random.rand(4 , 4) #dim uniform norma dist 0-1

array([[0.63318769, 0.94840679, 0.65870688, 0.29055259],
       [0.83766983, 0.10228187, 0.02697123, 0.86523705],
       [0.55525698, 0.59711738, 0.46991833, 0.43697672],
       [0.54358942, 0.4718054 , 0.85595956, 0.02121163]])

<img src="std-norm-dist.png" height="450px" width="450px">

In [42]:
np.random.randn(4 , 2) #standard normal dist/gaussian center= 0

array([[ 0.80736307,  1.52221355],
       [-1.08087844,  0.8931758 ],
       [ 0.86596231, -1.24841025],
       [ 1.21790177, -0.98354842]])

In [46]:
arr =np.random.randint(1,100, 25) #inc-exc range , num of values
arr

array([47, 44, 11, 59, 19, 80, 30, 59, 57, 56, 16,  1, 28, 93, 48, 13, 70,
       51, 27, 79, 57, 11, 57, 16, 66])

In [49]:
arr.reshape(5, 5 ) #not in place

array([[47, 44, 11, 59, 19],
       [80, 30, 59, 57, 56],
       [16,  1, 28, 93, 48],
       [13, 70, 51, 27, 79],
       [57, 11, 57, 16, 66]])

In [51]:
arr

array([47, 44, 11, 59, 19, 80, 30, 59, 57, 56, 16,  1, 28, 93, 48, 13, 70,
       51, 27, 79, 57, 11, 57, 16, 66])

In [53]:
arr.resize(5,5) # in place
arr

array([[47, 44, 11, 59, 19],
       [80, 30, 59, 57, 56],
       [16,  1, 28, 93, 48],
       [13, 70, 51, 27, 79],
       [57, 11, 57, 16, 66]])

In [59]:
print('Max val is {}  in location {}\nMin val is {} in location {}'.format(arr.max() ,arr.argmax() ,arr.min() , arr.argmin()))

Max val is 93  in location 13
Min val is 1 in location 11


In [60]:
arr.shape

(5, 5)

In [62]:
arr.dtype

dtype('int32')

In [68]:
sl = arr[0:2 , 3:5] #creates view to original array even if set in variable meaning 
               #the changes to the variable will change the value in the main
               # array
sl    

array([[59, 19],
       [57, 56]])

In [70]:
sl+=4
arr

array([[47, 44, 11, 67, 27],
       [80, 30, 59, 65, 64],
       [16,  1, 28, 93, 48],
       [13, 70, 51, 27, 79],
       [57, 11, 57, 16, 66]])

In [74]:
sl2 = arr[0:2 , 0:2].copy() #save a copy if you want to keep integrity of og
sl2-=30                     # array
sl2

array([[17, 14],
       [50,  0]])

In [75]:
arr

array([[47, 44, 11, 67, 27],
       [80, 30, 59, 65, 64],
       [16,  1, 28, 93, 48],
       [13, 70, 51, 27, 79],
       [57, 11, 57, 16, 66]])

In [83]:
arr[arr > 65]

array([67, 80, 93, 70, 79, 66])